---
title: "DSRs"
date: "`r Sys.Date()`"
author: "Julian Flowers"
output: 
   github_document:
always_allow_html: true
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(cache = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      echo = TRUE)

library(pacman)
p_load(tidyverse, devtools, plotly, readxl)

```

## Calculate case rate dsrs for local authorities

```{r}

URL <- "https://github.com/julianflowers12/test-and-trace/blob/master/create_case_dsr.R?raw=TRUE"

source_url(URL)

test <- case_dsrs_las(area = "utla")

tail(test$dsr)

```

### Get tiers

```{r tiers}

## get tier information

tiers <- read_csv("https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&metric=alertLevel&format=csv")

tiers <- tiers %>%
  filter(date == max(date))





```

## DSRs vs tiers

```{r fig.height= 14, fig.width=6}


dsr_tiers <- test$dsr %>%
  left_join(tiers, by = "areaName")

dsr_1 <- dsr_tiers %>%
  filter(date.x == max(date.x)) %>%
  ggplot(aes(reorder(areaName, value), value, fill = alertLevelName)) +
  geom_col() +
  labs(y = "Standardised case rate", 
       x = "Date", 
       title = "Age standardised 7-day rolling case rates per 100,000") +
  coord_flip() +
  theme(axis.text.y = element_text(size = 4))

dsr_1
# library(plotly)
# ggplotly(dsr_1)
```

```{r}

dsr_tiers %>%
    filter(date.x == max(date.x), !is.na(alertLevel)) %>%
    ggplot() +
    geom_density(aes(value, fill = alertLevelName), alpha = .4)



```

```{r fig.height= 20, fig.width=10}

dsr_tiers %>%
  group_by(areaName) %>%
  filter(date.x == max(date.x), !is.na(alertLevel)) %>%
  ggplot(aes(reorder(areaName, -value), value)) +
  geom_point(aes(colour = alertLevelName), size = 1) +
  geom_linerange(aes(ymax = uppercl, ymin = lowercl, colour = alertLevelName)) +
  coord_flip() +
  theme(axis.text = element_text(size = 6), 
        panel.background = element_blank(), 
        legend.position = "") +
  labs(x = "", y = "Rate") +
  viridis::scale_colour_viridis(discrete = TRUE, option = "D", direction = -1, name = "") +
  facet_wrap(~alertLevel, nrow = 1)


```

### Cluster analysis of ltla covid data

```{r clustering, fig.height= 6, fig.width=6}

library(Rtsne)
library(dbscan)
set.seed(123)
cl_data <- read_csv("https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&metric=newCasesBySpecimenDateChangePercentage&metric=newCasesBySpecimenDateRollingRate&metric=uniqueCasePositivityBySpecimenDateRollingSum&metric=newDeaths60DaysByDeathDateRollingRate&format=csv")


cl_data_1 <- cl_data %>%
  filter(date == max(date), 
         str_detect(areaCode, "^E")) %>%
  left_join(tiers, by = "areaName")

cl_data_2 <- cl_data_1 %>%
  select(5:8) %>%
  mutate_if(is.numeric, function(x) ifelse(is.na(x), median(x, na.rm = TRUE), x)) %>%
  mutate_if(is.numeric, scale) 

tsne <- cl_data_2 %>%
  as.matrix() %>%
  Rtsne::Rtsne() 

clust <- dbscan::hdbscan(tsne$Y, minPts = 9, gen_hdbscan_tree = TRUE)

data.frame(tsne$Y, clust$cluster) %>%
  ggplot(aes(X1, X2, colour = factor(clust.cluster))) +
  geom_point()

df <- data.frame(cl_data_1, cluster = clust$cluster)
df %>%
  select(areaName, cluster, alertLevelName) %>%
  arrange(cluster) %>%
  reactable::reactable(filterable = TRUE, searchable = TRUE)
```

```{r}
df %>%
  mutate_at(.vars = 5:8, scale) %>%
  group_by(cluster) %>%
  summarise(across(5:8, mean)) %>% 
  rename(change = newCasesBySpecimenDateChangePercentage, case_rate = newCasesBySpecimenDateRollingRate, pos_rate = uniqueCasePositivityBySpecimenDateRollingSum, deaths = newDeaths60DaysByDeathDateRollingRate) %>%
  pivot_longer(names_to = "metric", values_to = "values", cols = 2:5) %>%
  ggplot(aes(metric, values)) +
  geom_point() +
  geom_line(aes(group = cluster)) +
  geom_hline(yintercept = 0, colour = "red") +
  coord_polar() +
  facet_wrap(~cluster)
  


```
