---
title: "MSOA case maps"
output: github_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## 

```{r load-libraries, message = FALSE}
library(data.table)
library(tmap)
library(ggmap)
library(geojsonio)
library(tidyverse)
```


```{r download-data}
msoa <- fread("https://api.coronavirus.data.gov.uk/v2/data?areaType=msoa&metric=newCasesBySpecimenDateRollingRate&metric=newCasesBySpecimenDateChangePercentage&metric=newCasesBySpecimenDateDirection&format=csv")
msoa1 <- msoa[date == max(date), ]
```

```{r explore-data}

skimr::skim(msoa1)


```


```{r setup-mapping}

shp <- "https://opendata.arcgis.com/datasets/826dc85fb600440889480f4d9dbb1a24_0.geojson"

palette <- rev(viridis::viridis(15))
palette1 <- viridis::viridis(4, direction = -1)
credits <- "Contains ordnance survey data © \nCrown copyright and database right 2020"


## Download the data and convert to spatial polygon data frame
geodata <- geojson_read(shp, what = "sp")

# glimpse(geodata)
## Select England wards
seng <- subset(geodata, substr(msoa11cd, 1, 1) == "E")

## Join data to plot
seng@data <- left_join(seng@data, msoa1, by=c("msoa11cd" = "areaCode"))


```

```{r plot-change}

u <- tm_shape(seng) +
  tm_fill("newCasesBySpecimenDateDirection", style = "kmeans", palette = palette1 , n = 10,
          title = "Direction") +
  tm_credits( credits, size = 0.5, align = "right") +
  tm_layout(legend.outside = TRUE, 
            frame = FALSE) +
  tm_compass(position = c("left", "center")) + 
  tm_scale_bar(position = c("left", "center"))

u

```

```{r plot-percentage-change}

v <- tm_shape(seng) +
  tm_fill("newCasesBySpecimenDateChangePercentage", style = "kmeans", palette = palette , n = 10,
          title = "% change") +
  tm_credits( credits, size = 0.5, align = "right") +
  tm_layout(legend.outside = TRUE, 
            frame = FALSE) +
  tm_compass(position = c("left", "center")) + 
  tm_scale_bar(position = c("left", "center"))

v

```

```{r plot-rate}

w <- tm_shape(seng) +
  tm_fill("newCasesBySpecimenDateRollingRate", style = "fisher", palette = palette , n = 10,
          title = "Rate") +
  tm_credits( credits, size = 0.5, align = "right") +
  tm_layout(legend.outside = TRUE, 
            frame = FALSE) +
  tm_compass(position = c("left", "center")) + 
  tm_scale_bar(position = c("left", "center"))

w

```
